version: "3.0"

services:
  server:
    build:
      context: .
    restart: always
    ports:
      - "7171:7171"
      - "7172:7172"
    depends_on:
      - db
    networks:
      - db-network
    volumes:
      - tfs:/srv

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: forgottenserver
      MYSQL_PASSWORD: admin
      # Automatically creates a database
      MYSQL_DATABASE: forgottenserver
    volumes:
      # Saves all the data in ./db directory
      - ./db:/var/lib/mysql
      # Automatically executes schema.sql on startup
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - db-network

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

  website:
    image: webdevops/php-nginx:7.4-alpine
    container_name: "myaac-website"
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/tmp/web/
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./nginx/www:/tmp/web
      - ./data:/tmp/server/data
      - ./config.lua.dist:/tmp/server/config.lua
    networks:
      - db-network

networks:
  db-network:

volumes:
  tfs: 
